title: Notes
description: A simple site built using Github Pages and Jekyll.
theme: jekyll-theme-slate

main_navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Documentation"
    url: "/docs/"
  - title: "Contact"
    url: "/contact/"

