title: Notes
description: A simple site built using Github Pages and Jekyll.
theme: jekyll-theme-dinky

navigation:
  - Home: /
  - About: /about
  - Contact: /contact

paginate: 5
paginate_path: "/page:num/"
